config/routes.rb
Rails.application.routes.draw do
  root to: 'games#index'
  resources :games, only: [:index, :create, :new, :show]
  post '/objects/:game_id/:player_id', to: 'objects#create', as: 'new_object'
  get 'end_game/:id', to: 'games#end_game', as: 'end_game'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :object_cannon_games
  def players_name
    [first_player.name, second_player.name]
  end

  def first_player
    Player.find(self.first_player_id)
  end

  def second_player
    Player.find(self.second_player_id)
  end
end

app/models/object_cannon_game.rb
class ObjectCannonGame < ActiveRecord::Base
  belongs_to :player
  belongs_to :game
  before_save :set_attributes
  private
    def set_attributes
      self.total_attributes = GenerateRandom.generate_attribute
    end
end

class GenerateRandom
  def self.generate_attribute
    (rand(5) + solve_chance.to_i).to_i
  end

  def self.solve_chance
    posibilites = get_posibilities
    two_more = search_chance(posibilites, 20)
    five_more = search_chance(posibilites, 10)
    ten_more = search_chance(posibilites, 5)
    twenty_more = search_chance(posibilites, 1)
    posibility = rand(100)
    if two_more.include?(posibility)
      return 2
    elsif five_more.include?(posibility)
      return 5
    elsif ten_more.include?(posibility)
      return 10
    elsif twenty_more.include?(posibility)
      return 20
    else
      return 0
    end
  end

  def self.search_chance(total_chance, values)
    result = []
    (1..200).map do |num|
      element = total_chance[rand(total_chance.count)]
      if !result.include?(element)
        result << element
      end
      break if result.count == values
    end
    result
  end

  def self.get_posibilities
    values = []
    (1..100).map{ |num| values << num }
    values
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :object_cannon_games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def show
    @game = Game.find(params[:id])
  end

  def end_game
    @game = Game.find(params[:id])
    total_first_player = @game.object_cannon_games.where(player_id: @game.first_player.id).map(&:total_attributes).reduce(:+) || 0
    total_second_player = @game.object_cannon_games.where(player_id: @game.second_player.id).map(&:total_attributes).reduce(:+) || 0
    if total_first_player > total_second_player
      @game.winner_wall_health_remaining = 100 - total_second_player
      @game.winner = "Player 1"
    else
      @game.winner_wall_health_remaining = 100 - total_first_player
      @game.winner = "Player 2"
    end
    if @game.save
      redirect_to games_path
    else
      redirect_to game_path @game
    end
  end

  def create
    @game = Game.new
    first_player = Player.create(name: get_params[:first_player_id])
    second_player = Player.create(name: get_params[:second_player_id])
    @game.first_player_id = first_player.id
    @game.second_player_id = second_player.id
    if @game.save
      redirect_to game_path @game
    else
      render :new
    end
  end
  private
    def get_params
      params.require(:game).permit(:first_player_id, :second_player_id)
    end
end

app/controllers/objects_controller.rb
class ObjectsController < ApplicationController
  def create
    @object = ObjectCannonGame.new
    @object.game_id = params[:game_id]
    @object.player_id = params[:player_id]
    @object.save
    respond_to { |format| format.js }
  end
end

app/helpers/objects_helper.rb
module ObjectsHelper
end

app/views/games/_item_game.html.haml
%tr
  - game.players_name.each do |player_name|
    %td
      = player_name
  %td
    = game.winner_wall_health_remaining.to_i
  %td
    = game.winner

app/views/games/_object.html.haml
%tr
  %td
    = object.total_attributes

app/views/games/_table_games.html.haml
%table{ border: 1 }
  %thead
    %tr
      %td
        Player 1 Name
      %td
        Player 2 Name
      %td
        Winner Wall Health Remaining
      %td
        Winner
  %tbody
    - @games.each do |game|
      = render 'item_game', game: game

app/views/games/index.html.haml
= link_to "New Game", new_game_path

= render 'table_games'

app/views/games/new.html.haml
%h1
  New Game
= form_for @game do |f|
  = f.label :first_player_id
  = f.text_field :first_player_id, required: true
  = f.label :second_player_id
  = f.text_field :second_player_id, required: true
  = f.submit

app/views/games/show.html.haml
%h1
  = @game.players_name.join(" vs ")

.box{ class: "player-rival-#{@game.second_player.id} player-#{@game.first_player.id}" }
  .player-name
    Player 1:
    = @game.players_name[0]
  Wall:
  .wall
    = 100 - (@game.object_cannon_games.where(player_id: @game.second_player.id).map{ |object| object.total_attributes.to_i}.uniq.reduce(:+) || 0)
  = link_to "Atack", new_object_path(game_id: @game.id, player_id: @game.first_player.id), remote: true, method: :post
  .objects
    Your objects attacks:
  .totalobjects
    = @game.object_cannon_games.where(player_id: @game.first_player.id).map(&:total_attributes).reduce(:+) || 0

.box{ class: "player-rival-#{@game.first_player.id} player-#{@game.second_player.id}" }
  .player-name
    Player 2:
    = @game.players_name[1]
  Wall:
  .wall
    = 100 - (@game.object_cannon_games.where(player_id: @game.first_player.id).map{ |object| object.total_attributes.to_i}.uniq.reduce(:+) || 0)
  = link_to "Atack", new_object_path(game_id: @game.id, player_id: @game.second_player.id), remote: true, method: :post
  .objects
    Your objects attacks:
  .totalobjects
    = @game.object_cannon_games.where(player_id: @game.second_player.id).map(&:total_attributes).reduce(:+) || 0
:javascript
  $(document).ready( function() {
    $('.box.player-#{@game.second_player.id} a').click(function(){
      $('.box.player-#{@game.first_player.id} a').show();
      $(this).hide();
    });
    $('.box.player-#{@game.first_player.id} a').click(function(){
      $('.box.player-#{@game.second_player.id} a').show();
      $(this).hide();
    });
    $('.box.player-#{@game.second_player.id} a').hide();
  } );

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ObjectCannon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/objects/create.js.erb
$(".player-rival-<%= @object.player.id %> .wall").html( $(".player-rival-<%= @object.player.id %> .wall").html() - <%= @object.total_attributes %>);
$(".player-<%= @object.player.id %> .totalobjects").html( parseInt($(".player-<%= @object.player.id %> .totalobjects").html()) + <%= @object.total_attributes %>);
total = parseInt( $(".player-<%= @object.player.id %> .totalobjects").html());
if(total>100){window.location = "<%= end_game_path(@object.game.id) %>";};
console.log("Atacó <%= @object.player.name %>");